steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - functions
  - deploy
  - avgtemp-threshold_envvar
  - --source=gs://poc-cloudfunctions/env-triggerCF-temp.zip
  - --trigger-http
  - --runtime=python37
  - --allow-unauthenticated
  env:
  - 'avg_temp=40'
