steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - functions
  - deploy
  - avgtemp_threshold_envvar
  - --source=.
  - --trigger-http
  - --runtime=python37
  - --allow-unauthenticated
  env:
  - 'avg_temp=45'
  options:
  logging: CLOUD_LOGGING_ONLY
