steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - functions
  - deploy
  - avgtemp-threshold_envvar
  - --source=.
  - --trigger-http
  - --runtime=python37
  - --allow-unauthenticated
  serviceAccount: 'kafka-service-account@pg-us-e-app-588206.iam.gserviceaccount.com'
  env:
  - 'avg_temp=40'
